### ISSUE TITLE
中カテゴリの実装

### ISSUE THREAD

**Issue by ryo-k-nd** [ryo-k-nd/voila#15]
サブカテゴリ
後から修正/追加の可能性があり、編集部で更新ができるようにする

**Comment by ryo-k-nd** [comment]
From 鈴木さん

> 沖島さんよりご提案頂戴しまして、「ニュース」をカテゴリとしていれこみたいと思います。
> つきましては、デザインに影響が出ないよう、
> 「Vie」の中の「住まい」と「お金」を「住まい＆お金」として統合し、中カテゴリの一つに「ニュース」を入れる方向で解決できればと思います。

**Comment by ryo-k-nd** [comment]
@sayasuzuki @沖島さん

Contentful管理画面からサブカテゴリを追加できるようにしました。

サブカテゴリを追加する方法
![image](https://user-images.githubusercontent.com/30146784/85184986-5dfc3300-b292-11ea-9276-577899539eb5.png)

上記参考に、編集部の方で追加を進めていただくことは可能でしょうか。

上記で作成したSub Categoryは、記事(Blog Article)作成時に選択できるようになります。

**Comment by sayasuzuki** [comment]
・カテゴリ追加済み
・中カテゴリ内容変更に伴い、トップページへの反映をお願いできますでしょうか。
　「空港から市内まで」→「パリと地方都市」
　「パリと地方都市」→「海外旅行」
　「旅行」→「スポーツ・アウトドア」

**Comment by ryo-k-nd** [comment]
完了
設定方法はMTGで共有
