### ISSUE TITLE
天気予報の実装

### ISSUE THREAD

**Issue by ryo-k-nd** [ryo-k-nd/voila#19]
パリ
東京
最低最高気温

**Comment by ryo-k-nd** [comment]
@mito-newsdigeset いったんIssueわたします

- 都市ごとの最低気温、最高気温、予報(eg. 晴れ時々曇り)が取得できるAPI
- できればjson

**Comment by mito-newsdigeset** [comment]
@ryo-k-nd 
https://weatherstack.com/
これはいかがでしょうか
当日の天気を取得するのは無料。未来日の天気を取得するのは有料。

**Comment by ryo-k-nd** [comment]
AWs側完了
フロントとの繋ぎ込み

**Comment by ryo-k-nd** [comment]
小西

- [ ] AWS側の仕組みを水戸さんに共有

**Comment by ryo-k-nd** [comment]
テストコメ

**Comment by ryo-k-nd** [comment]
test

**Comment by ryo-k-nd** [comment]
test

**Comment by ryo-k-nd** [comment]
DONE
