### ISSUE TITLE
Site Title & Meta Description

### ISSUE THREAD

**Issue by ryo-k-nd** [ryo-k-nd/voila#2]
WEBサイトの各ページのTitleとDescriptionを用意/設置する

ページ一覧
https://docs.google.com/spreadsheets/d/1bkJ_6YXdtcKRUFU7USEVdMtIoSWCtvGw6ZWjeLeqNJ0/edit#gid=0

**Comment by ryo-k-nd** [comment]
小西メモ
- 共通Valueのセット
- 個別ページでのセット

**Comment by sayasuzuki** [comment]
https://docs.google.com/spreadsheets/d/1bkJ_6YXdtcKRUFU7USEVdMtIoSWCtvGw6ZWjeLeqNJ0/edit#gid=0
ページ説明が空欄のページは、内容がそのまま表示される形式で考えております！

**Comment by ryo-k-nd** [comment]
メモ: バックエンドの仕組みの実装は完了。

**Comment by ryo-k-nd** [comment]
@mito-newsdigeset 

共有です。
静的ページを水戸さんで作成することがあれば、下記のように指定できます。

- showSiteNameInTitle: ページのタイトル
- showSiteNameInTitle: trueにしておくと、「| Voila」が後ろにつきます
- pageDescription: Meta description
です。

```
<Layout>
 <SEO
   pageTitle="Voilà｜ヴォワラ・フランス生活情報メディア"
   showSiteNameInTitle="true"
   pageDescription=""
 />
...
```

**Comment by ryo-k-nd** [comment]
ページごとの入稿ステータスはスプレッドシートで管理
https://docs.google.com/spreadsheets/d/1bkJ_6YXdtcKRUFU7USEVdMtIoSWCtvGw6ZWjeLeqNJ0/edit#gid=0

**Comment by ryo-k-nd** [comment]
残り: 投稿ページを動的にcropして表示する処理

**Comment by ryo-k-nd** [comment]
> 投稿ページを動的にcropして表示する処理

Done
