### ISSUE TITLE
Heading指定位置がずれる

### ISSUE THREAD

**Issue by sayasuzuki** [ryo-k-nd/voila#26]
記事URL
https://app.contentful.com/spaces/zbyipzusy20r/entries/6xQ6C1fbT2v7KEwKsbJqDH

![スクリーンショット 2020-06-22 16 07 19](https://user-images.githubusercontent.com/66947913/85411732-9fc1fd80-b560-11ea-8d46-4f751951b98c.png)
![スクリーンショット 2020-06-22 16 07 32](https://user-images.githubusercontent.com/66947913/85411772-ad778300-b560-11ea-97e7-7b00328da24a.png)
![スクリーンショット 2020-06-22 16 07 39](https://user-images.githubusercontent.com/66947913/85411787-b36d6400-b560-11ea-96fd-acc712d1e436.png)

**Comment by sayasuzuki** [comment]
![スクリーンショット 2020-06-22 16 07 19](https://user-images.githubusercontent.com/66947913/85411732-9fc1fd80-b560-11ea-8d46-4f751951b98c.png)
![スクリーンショット 2020-06-22 16 07 32](https://user-images.githubusercontent.com/66947913/85411772-ad778300-b560-11ea-97e7-7b00328da24a.png)
![スクリーンショット 2020-06-22 16 07 39](https://user-images.githubusercontent.com/66947913/85411787-b36d6400-b560-11ea-96fd-acc712d1e436.png)

**Comment by ryo-k-nd** [comment]
@sayasuzuki 
左の入力画面と右のプレビュー画面で位置がずれるということですよね。
こちら、結論からいうと僕の方で修正ができません。

調べてみたのですが、Contentfulのプレビュー機能の問題で、記事が長くなってきた際に他のマークダウン式エディタでもよく起こる問題らしいです。

Contentfulの記事入力フォームはマークダウンとリッチテキスト式の2種類がありますが、
後者では機能が限定されている（そもそもプレビューができない、全画面編集ができない、表などが使えないなど）ため、
今回は我慢していただく必要があります。

**Comment by sayasuzuki** [comment]
了解です！
