### ISSUE TITLE
[記事詳細]Contentful上で指定した書式が反映されない

### ISSUE THREAD

**Issue by mito-newsdigeset** [ryo-k-nd/voila#28]
Contentful上で指定した書式がHTMLのタグに正常に変換されない。
(1行目の指定のみ反映されている？)

https://reverent-almeida-73053a.netlify.app/post/natsume-ten-dreaming-nights/

サイト上で以下の様に記号?が表示されてしまう
![Screenshot 2020-06-29 at 17 48 09](https://user-images.githubusercontent.com/66747084/86033410-cedce100-ba30-11ea-9252-3b22305378b5.png)

**Comment by ryo-k-nd** [comment]
Headingができてない
