### ISSUE TITLE
サイドバーの記事実装 人気記事、おすすめ記事

### ISSUE THREAD

**Issue by ryo-k-nd** [ryo-k-nd/voila#35]
画像のlazy loadもやる

**Comment by ryo-k-nd** [comment]
@mito-newsdigeset 

下記、サイドバーの部分がまだ中途半端なのですが、水戸さんやってみますか？

おすすめ記事を取得する処理は既に書いているので、残る作業は下記のような感じかなと思ってます。

- gatsby-imageを使って画像取得の処理を書き直す
- 人気記事の取得処理（ src/pages/index.js と src/utils/generateContentByPageViews.js を見れば大体処理わかると思います。）
- スタイルを調整

![image](https://user-images.githubusercontent.com/30146784/87524268-3d07e180-c688-11ea-96fb-c02ac5726aa7.png)

**Comment by mito-newsdigeset** [comment]
@ryo-k-nd 
こちら対応しました。
サムネ取得など対応したため、generateContentByPageViews.jsとTOPの人気の記事部分も改修しました。
ご確認ください

**Comment by ryo-k-nd** [comment]
小西のほうでコードチェック
