### ISSUE TITLE
記事内の引用(<blockquote>)のStyle

### ISSUE THREAD

**Issue by ryo-k-nd** [ryo-k-nd/voila#38]
![Screenshot 2020-07-19 at 20 39 06](https://user-images.githubusercontent.com/30146784/87882381-f572b400-c9ff-11ea-801a-91cff686fc0b.png)

Quoteの部分は、`<blockquote>`タグ自体は発行されてるので、もうちょっとわかりやすいStyleをあてたほうがいいかも。

codeblockはほぼ使わないと思うけど、時間ある時に prismjs あたりを使う予定なのでそのままで大丈夫です

**Comment by mito-newsdigeset** [comment]
対応完了。
7/27(月)のMTGで確認してもらう

**Comment by mito-newsdigeset** [comment]
07/27
鈴木さんからのフィードバックを反映。
