### ISSUE TITLE
[記事ページ]PCでサイドバーにあるスクエアバナーをモバイル時にリード下に出したい

### ISSUE THREAD

**Issue by mito-newsdigeset** [ryo-k-nd/voila#44]
PCではサイドバーにあるスクエアバナーを、モバイル時はリード下に出したい。

フロント側で制御か、バックエンド側で制御か、どちらが正解かわからないのでご相談。

**Comment by ryo-k-nd** [comment]
@mito-newsdigeset 
フロント制御にしてもらっていいでしょうか。
画像二枚読み込むことになりますが、同じ画像の読み込みはトラフィック食わないので大丈夫です。

**Comment by mito-newsdigeset** [comment]
@ryo-k-nd 
スクエアバナーの表示部分をコンポーネント化し、post.jsのリード下とsidebar.jsで呼び出すようにしました。
PCではpost.jsを非表示にしています。
